# Numpy 

In [1]:
# Direct multilication of list is not posibble
a=[1,2,3]
b=[4,5,6]
# a*b= ERROR

In [2]:
import numpy as np

# The basics


In [7]:
a=np.array([1,2,3]) # 1-dimensional array 

type(a) # n-dimensional array

numpy.ndarray

In [9]:
print(a)

[1 2 3]


In [13]:
b=np.array([[1,2,3],[4,5,6]]) # 2-dimensional array

In [14]:
print(b)

[[1 2 3]
 [4 5 6]]


In [15]:
type(b)


numpy.ndarray

In [23]:
# Get dimension
print(b.ndim)
print(a.ndim)


2
1


In [24]:
# Get shape
a.shape 

(3,)

In [26]:
b.shape # 2 row

(2, 3)

In [27]:
# Get type
a.dtype

dtype('int32')

In [28]:
b.dtype

dtype('int32')

In [33]:
a=np.array([1,2,3],dtype="int16")

In [31]:
a.dtype 

dtype('int16')

In [35]:
# Get itemsize
a.itemsize # returns the byte size

2

In [37]:
a=np.array([1,2,3],dtype="int32")
a.itemsize

4

In [42]:
# Get Total size
print(a.size*a.itemsize)
print(a.nbytes)

12
12


#  Accessing/changing specific elements,rows,columns,etc

In [43]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [44]:
# Get a specific element
a[1,5] #2nd row and  6th element


13

In [46]:
a[1,-2]

13

In [49]:
# Get a specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [53]:
# Get a specific column 
a[:,1]

array([2, 9])

In [59]:
#Getting a litile more fancy [startindex:endindex:stepssize]
a[0,1:7:2]

array([2, 4, 6])

In [62]:
a[0,1:-1:2]

array([2, 4, 6])

In [66]:
a[0,5]=20
print(a)

a[:,2]=22
print(a)

[[ 1  2 22  4  5 20  7]
 [ 8  9 22 11 12 13 14]]
[[ 1  2 22  4  5 20  7]
 [ 8  9 22 11 12 13 14]]


# 3-D example

In [93]:
x=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(x)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [94]:
print(x.shape) # (no of matrices,2X2 matix)

(3, 2, 2)


In [95]:
# Get specific element (work otside in)
x[:,1,:] # all 1st  row of each matrix

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [97]:
x[:,1,0]

array([ 3,  7, 11])

In [98]:
x[1,1,1]

8

In [111]:
# replace
x[:,1,:]=[[31,41],[71,81],[111,121]]
x

array([[[  1,   2],
        [ 31,  41]],

       [[  5,   6],
        [ 71,  81]],

       [[  9,  10],
        [111, 121]]])

# Initializing different types of arrays

In [112]:
# All zeros matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [115]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [116]:
np.zeros((2,3,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [117]:
#All 1's matrix
np.ones(4)

array([1., 1., 1., 1.])

In [124]:
k=np.ones((3,2))

In [123]:
#Any other number
np.full((2,2),(6,3)) #((nXn matrix),values)

array([[6, 3],
       [6, 3]])

In [125]:
#Any other number (full_like)
np.full_like(k,4)

array([[4., 4.],
       [4., 4.],
       [4., 4.]])

In [127]:
# Random decimal number
np.random.rand(4,2,3)

array([[[0.3693803 , 0.06903726, 0.27000961],
        [0.74020929, 0.51682568, 0.21971906]],

       [[0.09290459, 0.86476741, 0.19805804],
        [0.25944561, 0.1359469 , 0.00883534]],

       [[0.12629139, 0.3677698 , 0.94817239],
        [0.2464989 , 0.97404067, 0.36358016]],

       [[0.61455613, 0.52363762, 0.62092318],
        [0.21807507, 0.74433477, 0.75823212]]])

In [128]:
np.random.random_sample(k.shape)

array([[0.8801076 , 0.3648845 ],
       [0.88280067, 0.02118958],
       [0.0685131 , 0.98101285]])

In [129]:
#Random integer values
np.random.randint(7)

3

In [138]:
np.random.randint(1,9,size=(4,4)) #(from , to ,nXn matrix)

array([[3, 2, 7, 2],
       [3, 8, 3, 8],
       [2, 5, 6, 6],
       [7, 8, 5, 8]])

In [140]:
#The identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [150]:
#Repeat an array
arr=np.array([1,2,3])
r1=np.repeat(arr,3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [158]:
ar=np.array([4,5,6])
r2=np.repeat(ar,3,axis=0)
print(r2)
ar1=np.array([[4,5,6]])
r3=np.repeat(ar1,4,axis=0)
print(r3)


[4 4 4 5 5 5 6 6 6]
[[4 5 6]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [194]:
l=np.ones((5,5))
l
z=np.zeros((3,3))
z[1,1]=9
z
l[1:4,1:4]=z
l

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Be careful while copying the array

In [203]:
a1=np.array([1,2,3])
b1=a1
b1[0]=10
print(b1)
print(a1) #both the variable occupy the change

[10  2  3]
[10  2  3]


In [208]:
b1=a1.copy()
b1[0]=20
print(b1)
print(a1)

[20  2  3]
[10  2  3]



# Mathematics

In [209]:
p=np.array([1,2,3,4,5,6])

In [210]:
p+3

array([4, 5, 6, 7, 8, 9])

In [211]:
p*2

array([ 2,  4,  6,  8, 10, 12])

In [215]:
p+=2 #p=p+2
p

array([ 5,  6,  7,  8,  9, 10])

# Linear Algebra

In [217]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [218]:
# Find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0